# section is used for building blocks which can then be pulled in
# to compose an environment configuration.
components:

  log4j-logging: &log4j-logging
    cucumber.log4j2.config.file: log4j.properties

  cucumber-multithreading: &cucumber-multithreading
    cucumber.threads: 1

  cucumber-all-armenotechTestEnv-constraints: &cucumber-all-armenotechTestEnv-constraints
    cucumber.tags: "@CI"

  armenotechTestEnv-endpoints: &armenotechTestEnv-endpoints
    base.uri: https://payments-api.armenotech.dev #test env
    groovy.execute.endpoint: #test armenotechTestEnv env
    admin.security.endpoint: #test armenotechTestEnv env

  armenotechTestEnv-properties: &armenotechTestEnv-properties
    create.customer.strategy: api #test armenotechTestEnv env strategy
    create.auth.token.strategy: api #test armenotechTestEnv env strategy

  automation-base-settings: &automation-base-settings
    <<: *log4j-logging
    <<: *cucumber-multithreading
    cucumber.feature.path: src/test/resources/features
    cucumber.stepdefs.package: com

environments:

  armenotechTestEnv: &armenotechTestEnv
    <<: *automation-base-settings
    <<: *cucumber-all-armenotechTestEnv-constraints
    <<: *armenotechTestEnv-endpoints
    <<: *armenotechTestEnv-properties